PREFIX drugbank: <http://www4.wiwiss.fu-berlin.de/drugbank/resource/drugbank/>
PREFIX kegg: <http://bio2rdf.org/ns/kegg#>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX bio2RDF: <http://bio2rdf.org/ns/bio2rdf#>
PREFIX purl: <http://purl.org/dc/elements/1.1/>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX dailymed: <http://www4.wiwiss.fu-berlin.de/dailymed/resource/dailymed/>
PREFIX route: <http://www4.wiwiss.fu-berlin.de/dailymed/resource/routeOfAdministration/>
SELECT DISTINCT ?drugLabel ?ingredientLabel
WHERE {
?drug dailymed:fullName ?drugLabel .
?drug dailymed:routeOfAdministration route:Oral .
?drug dailymed:activeIngredient ?ingredient .
?ingredient rdfs:label ?ingredientLabel .
}

