PREFIX affymetrix: <http://bio2rdf.org/affymetrix_vocabulary:>
PREFIX tcga: <http://tcga.deri.ie/schema/>
PREFIX diseasome: <http://www4.wiwiss.fu-berlin.de/diseasome/resource/diseasome/>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT *
WHERE {
  ?probe a affymetrix:Probeset .
  ?probe affymetrix:x-geneid ?gene .
  ?probe affymetrix:species-scientific-name "Homo sapiens" .
  ?probe affymetrix:chromosomal-location ?loc .

  ?gene tcga:chromosome ?chromosome .
  ?gene tcga:start ?chrstart .
  ?gene tcga:stop ?chrstop .
  ?gene tcga:Strand ?strand .

  ?dgene diseasome:geneId ?gene .
  ?dgene diseasome:hgncId ?hgnc .
  ?dgene owl:sameAs ?dgenesame .
  ?dgene rdfs:label ?dgenelabel .

  ?disease diseasome:associatedGene ?dgene .
  ?disease diseasome:name ?dn .
  ?disease diseasome:possibleDrug ?drug .
  ?disease diseasome:class ?diseaseclass
}


